name: Terraform CI and Website Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Init Format Validate and Deploy Website
    runs-on: ubuntu-latest

    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      WEB_STORAGE_ACCESS_KEY: ${{ secrets.WEB_STORAGE_ACCESS_KEY }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Deploy website files to Azure Static Website
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          az storage blob upload-batch \
            --account-name iacwebc9ti3i \
            --account-key "$WEB_STORAGE_ACCESS_KEY" \
            --destination '$web' \
            --source ../app \
            --overwrite true
